# Generated by Django 4.0.5 on 2022-06-10 11:25

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=255, populate_from='name', unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('composition', models.TextField(verbose_name='Состав')),
                ('packaging', models.TextField(verbose_name='Упаковка')),
                ('energy_value', models.TextField(verbose_name='Энеретическая ценность')),
                ('manufacturer', models.TextField(verbose_name='Производитель')),
                ('shelf_life', models.TextField(verbose_name='Срок годности')),
                ('certificates', models.TextField(verbose_name='Сертификаты')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='sweet_shop.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Сырок',
                'verbose_name_plural': 'Сырки',
                'ordering': ['-time_create'],
            },
        ),
    ]
