# Generated by Django 4.0.5 on 2022-06-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_shop', '0002_alter_category_slug_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='sweet_shop__name_f02a94_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='sweet_shop__price_c8046d_idx'),
        ),
    ]
